#!/usr/bin/env bash
# Bootstraps Phase 05 from a clean cluster.
# Installs Longhorn and deploys the canonical todo-app chart.
#
# Prerequisites:
#   - kubectl pointing at a running cluster with iscsiadm on every node
#   - helm installed
#   - application/chart present at the repository root
#   - .env filled in (copy from .env.example)
#
# Usage: ./bootstrap.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOLUTION="$SCRIPT_DIR/.."
REPO_ROOT="$(cd "$SOLUTION/../../.." && pwd)"
CHART_DIR="$REPO_ROOT/application/chart"
CHART_VALUES="$SOLUTION/apps/todo-app/values/prod-values.yaml"
ENV_FILE="$SCRIPT_DIR/.env"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; CYAN='\033[0;36m'; NC='\033[0m'
info() { printf "${GREEN}[+]${NC} %s\n" "$*"; }
warn() { printf "${YELLOW}[!]${NC} %s\n" "$*"; }
err()  { printf "${RED}[✗]${NC} %s\n" "$*" >&2; exit 1; }
step() { printf "\n${CYAN}━━━  %s  ━━━${NC}\n" "$*"; }
validate_uri_safe() {
  local value="$1"
  local name="$2"
  [[ "$value" =~ ^[A-Za-z0-9._~-]+$ ]] || err "$name must only contain URI-safe characters: A-Z a-z 0-9 . _ ~ -"
}

# ── Load configuration ────────────────────────────────────────────
step "Loading configuration"
[[ -f "$ENV_FILE" ]] || err ".env not found — copy .env.example to .env and fill in your values."
# shellcheck source=/dev/null
source "$ENV_FILE"
: "${DOCKERHUB_USER:?DOCKERHUB_USER not set in .env}"
: "${IMAGE_TAG:?IMAGE_TAG not set in .env}"
RELEASE_NAME="${RELEASE_NAME:-my-app}"
CHART_REGISTRY="${CHART_REGISTRY:-registry-1.docker.io/${DOCKERHUB_USER}}"
CHART_VERSION="${CHART_VERSION:-}"
if [[ -z "$CHART_VERSION" ]]; then
  CHART_VERSION="$(awk -F': *' '$1 == "version" { gsub(/"/, "", $2); print $2; exit }' "$CHART_DIR/Chart.yaml")"
fi
[[ -n "$CHART_VERSION" ]] || err "CHART_VERSION is not set and could not be read from application/chart/Chart.yaml"
# Phase 05 installs the canonical chart straight from application/chart (local).
# Publishing/consuming via OCI is introduced in Phase 06 (publish-chart.sh), so
# this phase stays self-contained and needs no external chart registry. Override
# TODO_APP_CHART (e.g. oci://${CHART_REGISTRY}/todo-app) in .env to pull from OCI.
TODO_APP_CHART="${TODO_APP_CHART:-local}"
if [[ "$TODO_APP_CHART" == "local" ]]; then
  TODO_APP_CHART="$CHART_DIR"
fi
info "Release name: $RELEASE_NAME"
info "todo-app chart: $TODO_APP_CHART"
if [[ "$TODO_APP_CHART" == oci://* ]]; then
  info "todo-app chart version: $CHART_VERSION"
fi

TODO_APP_SET_ARGS=(
  --set "frontend.image.repository=docker.io/${DOCKERHUB_USER}/todo-frontend"
  --set "frontend.image.tag=${IMAGE_TAG}"
  --set "backend.image.repository=docker.io/${DOCKERHUB_USER}/todo-backend"
  --set "backend.image.tag=${IMAGE_TAG}"
)

if [[ -n "${POSTGRES_USER:-}" ]]; then
  validate_uri_safe "$POSTGRES_USER" "POSTGRES_USER"
  TODO_APP_SET_ARGS+=(--set-string "postgres.bootstrap.credentials.user=${POSTGRES_USER}")
fi
if [[ -n "${POSTGRES_DB:-}" ]]; then
  validate_uri_safe "$POSTGRES_DB" "POSTGRES_DB"
  TODO_APP_SET_ARGS+=(--set-string "postgres.bootstrap.credentials.database=${POSTGRES_DB}")
fi
if [[ -n "${POSTGRES_PASSWORD:-}" ]]; then
  validate_uri_safe "$POSTGRES_PASSWORD" "POSTGRES_PASSWORD"
  TODO_APP_SET_ARGS+=(--set-string "postgres.bootstrap.credentials.password=${POSTGRES_PASSWORD}")
  info "PostgreSQL password: fixed from .env"
else
  info "PostgreSQL password: generated by the Helm hook if the Secret does not exist"
fi

TODO_APP_CHART_ARGS=("$TODO_APP_CHART")
if [[ "$TODO_APP_CHART" == oci://* ]]; then
  TODO_APP_CHART_ARGS+=(--version "$CHART_VERSION")
fi

# ── Check required tools ──────────────────────────────────────────
step "Checking prerequisites"
command -v kubectl &>/dev/null || err "kubectl not found — install it first."
command -v helm    &>/dev/null || err "helm not found — install it first."
kubectl cluster-info &>/dev/null || err "Cannot reach cluster. Check your kubectl context with: kubectl config current-context"
info "Cluster: $(kubectl config current-context)"
info "kubectl $(kubectl version --client --short 2>/dev/null || kubectl version --client | head -1)"
info "helm $(helm version --short)"

# ── Step 1: Longhorn ──────────────────────────────────────────────
step "Installing Longhorn"

# Verify iscsiadm is reachable before wasting time on the install
if ! iscsiadm --version &>/dev/null 2>&1; then
  warn "iscsiadm not found on this machine."
  warn "On k3s/Linux: sudo apt install open-iscsi && sudo systemctl enable --now iscsid"
  warn "On Talos: rebuild nodes with the iscsi-tools extension from factory.talos.dev"
  err  "Fix iscsiadm first — Longhorn will crash without it."
fi

helm repo add longhorn https://charts.longhorn.io --force-update &>/dev/null
helm repo update longhorn &>/dev/null
helm dependency update "$SOLUTION/apps/longhorn"

# Pre-create the namespace with the privileged Pod Security Admission labels
# Longhorn requires. Helm 4 needs the target namespace to exist up front, and
# pre-creating it (rather than --create-namespace) keeps install and upgrade
# idempotent — same approach as Phase 06.
kubectl apply -f - <<'EOF'
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
EOF

helm upgrade --install cluster-longhorn "$SOLUTION/apps/longhorn" \
  -f "$SOLUTION/apps/longhorn/values/prod-values.yaml" \
  -n longhorn \
  --wait --timeout 5m

info "Longhorn installed"
kubectl get storageclass | grep longhorn || warn "longhorn StorageClass not found — check Longhorn pods"

# ── Step 2: Deploy todo-app ───────────────────────────────────────
step "Deploying todo-app"

kubectl create namespace todo --dry-run=client -o yaml | kubectl apply -f -

helm upgrade --install "$RELEASE_NAME" "${TODO_APP_CHART_ARGS[@]}" \
  -f "$CHART_VALUES" \
  "${TODO_APP_SET_ARGS[@]}" \
  -n todo \
  --wait --timeout 3m

info "todo-app deployed"

# ── Verify ────────────────────────────────────────────────────────
step "Verification"

echo ""
echo "Nodes:"
kubectl get nodes -o wide

echo ""
echo "Longhorn pods:"
kubectl get pods -n longhorn --no-headers | awk '{printf "  %-50s %s\n", $1, $3}'

echo ""
echo "todo-app pods:"
kubectl get pods -n todo --no-headers | awk '{printf "  %-50s %s\n", $1, $3}'

echo ""
echo "PVC:"
kubectl get pvc -n todo

echo ""
info "Bootstrap complete."
info "Frontend NodePort: $(kubectl get svc -n todo -o jsonpath='{.items[?(@.spec.type=="NodePort")].spec.ports[0].nodePort}' 2>/dev/null || echo 'check kubectl get svc -n todo')"
