apiVersion: v2
name: cluster-sealed-secrets
description: Installs the Bitnami Sealed Secrets controller into kube-system
type: application
version: 1.0.0
dependencies:
  - name: sealed-secrets
    version: 2.18.3
    repository: https://bitnami-labs.github.io/sealed-secrets
