---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-secrets
  namespace: harbor
spec:
  encryptedData:
    admin_password: AgCbc6jgF5yECdEkHVVz1fETf1DtTBujZCXZwsUC5w07QatiKJq7pPisGcgDj2vuL+cReVCWMoDSNGGXWBgWz/owyJelaSaVxnWA8FuIQZH4nG3WL3RKq/QlSe8tzMaB8PTpL8R+UuV32sro1uFAuAiNrcj24pPzdT7+70opedM+A/NTH2rpescoVvs+OfwBrYqXvHf372K9B5P+WKxDYPE9AjaKt05xvDyUFduvwBURRVUpmxGznb9e5VVzo6XASdNBbXRuPeAXPLTJUqRUEsOw5jWaFl3ea9hyZTaLB85mOknXrGpt405YBPTkILU+Fe8GAFFNly6kZKP+uPXoqWyMNyZ25Fqwk0hIsZoY4S7zfcVX6WLtntdkST6I14NAClKNWmrO1Wf1cgkU/Vi18lorqfPgvUWduXA9KnjKd+y74Q5vZkdtiQCLv2Pjb/s0LCZlUhDWplZ77jDbRmJQZ0rT/QGIYaSaO8TOYvGf4ei/5U2jOWstAcS976E/3DsDEwaa+WubJpWjFeCqqhCuP1C0Xc0fmfFVSki4uQ/ZdhAGcSyF+epc9gmOw4S5LNFzzWRpzRmRP9CIPvCUzdPghDaAvf1+HxFslWD7xfsro3rdAI91jNpKgY8YkFv/9I6/rzbVGMPIUeSvvOuvQ93BBNdk7iezlPEM4H/rQTOotyWZd3Ubqyw4RbLSqNqNnSE3F2OtQrqPx3PUb/Luow==
    secret_key: AgB7Dy5Fo8RbLq97tw7m38M1yO0tNABWsu2egcPAehSS/TdxVD8Xl6y0wSAw2JoZxd5DFZHmf0oePxIieo4NxZOFZfcX7zYcjwO+e1mq93hObo7jaIvl7TQQLO7ZiRs4Y40YMpv9HmaAgnYLQStSM/Cyom+Mt6letUDLz7dkC4w6Zj29aHV1rBCPEVByAv6SCxd8hPLF6aSJrrcfDWOpJ3Nl5AOgEvNyjXcsdOU4Zx/9hmF8cVzTIQcSU3RyXW5swinZAxhLTtQ3cgAspNfob9CLpLmM4yaO2OSVFQoDiFuuvsZcQe7EU4ke7wvWl2QKXSFwZ3yChuG4FI+cl/XjBF8b5QP5qiDSg3/9znBeq8h74Hs5U0k/N/mNcJUazqnbHf3Wya6F3Lt89QPFujNULZzvDMbd196VLZ9KaHQofXp+iKmHCdPsK2VogP0+LSzOzp6al6qqPiQUwnqvvwHJ7uU8h4V0T48kJreDzFmQg0F0y5TsWhESms75Y8+oLTgjKotLr3NOZfYSSjipkfahny12d+wbCk6/6hU704cAjhQ5wW3Adgvmy4v/+iZhatrJ8vTR0H0FUN7ikGVCG6XdpoTn81dKIqSJlaGE/8MrhvsW72mSwX0QA1AbUvMbwCeov+mhA9E4lRsqZs1cZO+L7NHmyJCpjBOKfxVwj6M6Sux4GImoALbfluSn26DJ4qVV0dgQ/WeD1a5JMfQMH15EafLg
  template:
    metadata:
      name: harbor-secrets
      namespace: harbor
