#!/usr/bin/env bash
# Bootstraps Phase 08 from a clean cluster.
# Installs MetalLB, cert-manager, Envoy Gateway, Longhorn, Authentik, Harbor,
# pushes images to Harbor, and deploys todo-app pulling from the private registry.
#
# Prerequisites:
#   - kubectl pointing at a running cluster with iscsiadm on every node
#   - helm installed
#   - docker CLI installed (for pushing images to Harbor)
#   - .env filled in (copy from .env.example)
#   - Application images built locally: frontend:<tag>, backend:<tag>
#
# Chart source: defaults to the LOCAL canonical chart (application/chart).
# After running scripts/publish-chart.sh, set TODO_APP_CHART=oci://harbor.local/todo/todo-app
# in .env to install from Harbor OCI.
#
# Usage: ./bootstrap.sh
#
# Teardown (manual):
#   helm uninstall "$RELEASE_NAME" -n todo
#   helm uninstall cluster-harbor -n harbor
#   helm uninstall cluster-authentik -n authentik
#   helm uninstall cluster-longhorn -n longhorn
#   helm uninstall cluster-envoy-gateway -n envoy-gateway
#   helm uninstall cluster-cert-manager-issuers -n cert-manager
#   helm uninstall cluster-cert-manager -n cert-manager
#   helm uninstall cluster-metallb -n metallb-system
#   kubectl delete namespace todo harbor authentik longhorn envoy-gateway cert-manager metallb-system
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOLUTION="$SCRIPT_DIR/.."
REPO_ROOT="$(cd "$SOLUTION/../../.." && pwd)"
CHART_DIR="$REPO_ROOT/application/chart"
CHART_VALUES="$SOLUTION/apps/todo-app/values/prod-values.yaml"
ENV_FILE="$SCRIPT_DIR/.env"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; CYAN='\033[0;36m'; NC='\033[0m'
info() { printf "${GREEN}[+]${NC} %s\n" "$*"; }
warn() { printf "${YELLOW}[!]${NC} %s\n" "$*"; }
err()  { printf "${RED}[✗]${NC} %s\n" "$*" >&2; exit 1; }
step() { printf "\n${CYAN}━━━  %s  ━━━${NC}\n" "$*"; }
validate_uri_safe() {
  local value="$1"
  local name="$2"
  [[ "$value" =~ ^[A-Za-z0-9._~-]+$ ]] || err "$name must only contain URI-safe characters: A-Z a-z 0-9 . _ ~ -"
}

# ── Load configuration ────────────────────────────────────────────
step "Loading configuration"
[[ -f "$ENV_FILE" ]] || err ".env not found — copy .env.example to .env and fill in your values."
# shellcheck source=/dev/null
source "$ENV_FILE"
: "${IMAGE_TAG:?IMAGE_TAG not set in .env}"
: "${AUTHENTIK_SECRET_KEY:?AUTHENTIK_SECRET_KEY not set in .env — generate one with: openssl rand -base64 36}"
: "${AUTHENTIK_BOOTSTRAP_PASSWORD:?AUTHENTIK_BOOTSTRAP_PASSWORD not set in .env}"
: "${AUTHENTIK_PG_PASSWORD:?AUTHENTIK_PG_PASSWORD not set in .env}"
: "${HARBOR_ADMIN_PASSWORD:?HARBOR_ADMIN_PASSWORD not set in .env}"
: "${HARBOR_SECRET_KEY:?HARBOR_SECRET_KEY not set in .env — generate one with: openssl rand -hex 8}"
RELEASE_NAME="${RELEASE_NAME:-my-app}"
HARBOR_PROJECT="${HARBOR_PROJECT:-todo}"
HARBOR_HOST="${HARBOR_HOST:-harbor.local}"
HARBOR_USER="${HARBOR_USER:-admin}"
AUTHENTIK_BOOTSTRAP_EMAIL="${AUTHENTIK_BOOTSTRAP_EMAIL:-}"
CHART_VERSION="${CHART_VERSION:-}"
if [[ -z "$CHART_VERSION" ]]; then
  CHART_VERSION="$(awk -F': *' '$1 == "version" { gsub(/"/, "", $2); print $2; exit }' "$CHART_DIR/Chart.yaml")"
fi
[[ -n "$CHART_VERSION" ]] || err "CHART_VERSION is not set and could not be read from application/chart/Chart.yaml"
TODO_APP_CHART="${TODO_APP_CHART:-local}"
if [[ "$TODO_APP_CHART" == "local" ]]; then
  TODO_APP_CHART="$CHART_DIR"
fi
info "Release name: $RELEASE_NAME"
info "todo-app chart: $TODO_APP_CHART"
if [[ "$TODO_APP_CHART" == oci://* ]]; then
  info "todo-app chart version: $CHART_VERSION"
fi

TODO_APP_SET_ARGS=(
  --set "frontend.image.repository=${HARBOR_HOST}/${HARBOR_PROJECT}/frontend"
  --set "frontend.image.tag=${IMAGE_TAG}"
  --set "backend.image.repository=${HARBOR_HOST}/${HARBOR_PROJECT}/backend"
  --set "backend.image.tag=${IMAGE_TAG}"
)

if [[ -n "${POSTGRES_USER:-}" ]]; then
  validate_uri_safe "$POSTGRES_USER" "POSTGRES_USER"
  TODO_APP_SET_ARGS+=(--set-string "postgres.bootstrap.credentials.user=${POSTGRES_USER}")
fi
if [[ -n "${POSTGRES_DB:-}" ]]; then
  validate_uri_safe "$POSTGRES_DB" "POSTGRES_DB"
  TODO_APP_SET_ARGS+=(--set-string "postgres.bootstrap.credentials.database=${POSTGRES_DB}")
fi
if [[ -n "${POSTGRES_PASSWORD:-}" ]]; then
  validate_uri_safe "$POSTGRES_PASSWORD" "POSTGRES_PASSWORD"
  TODO_APP_SET_ARGS+=(--set-string "postgres.bootstrap.credentials.password=${POSTGRES_PASSWORD}")
  info "PostgreSQL password: fixed from .env"
else
  info "PostgreSQL password: generated by the Helm hook if the Secret does not exist"
fi

TODO_APP_CHART_ARGS=("$TODO_APP_CHART")
if [[ "$TODO_APP_CHART" == oci://* ]]; then
  TODO_APP_CHART_ARGS+=(--version "$CHART_VERSION")
fi

# ── Check required tools ──────────────────────────────────────────
step "Checking prerequisites"
command -v kubectl &>/dev/null || err "kubectl not found — install it first."
command -v helm    &>/dev/null || err "helm not found — install it first."
command -v docker  &>/dev/null || err "docker not found — install it to push images to Harbor."
kubectl cluster-info &>/dev/null || err "Cannot reach cluster. Check your kubectl context with: kubectl config current-context"
info "Cluster: $(kubectl config current-context)"
info "kubectl $(kubectl version --client --short 2>/dev/null || kubectl version --client | head -1)"
info "helm $(helm version --short)"
info "docker $(docker version --format '{{.Client.Version}}' 2>/dev/null || echo 'version unknown')"

# ── Step 1: Namespaces ────────────────────────────────────────────
step "Creating namespaces"

kubectl apply -f - <<'EOF'
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
    expose-via-gateway: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik
  labels:
    expose-via-gateway: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
  labels:
    expose-via-gateway: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: todo
  labels:
    expose-via-gateway: "true"
EOF

info "Namespaces ready"

# ── Step 2: MetalLB ───────────────────────────────────────────────
step "Installing MetalLB"

helm repo add metallb https://metallb.github.io/metallb --force-update &>/dev/null
helm repo update metallb &>/dev/null
helm dependency update "$SOLUTION/apps/metallb"

helm upgrade --install cluster-metallb "$SOLUTION/apps/metallb" \
  -f "$SOLUTION/apps/metallb/values/prod-values.yaml" \
  -n metallb-system \
  --wait --timeout 3m

info "MetalLB installed"

# ── Step 3: cert-manager ──────────────────────────────────────────
step "Installing cert-manager"

helm dependency update "$SOLUTION/apps/cert-manager"

helm upgrade --install cluster-cert-manager "$SOLUTION/apps/cert-manager" \
  -f "$SOLUTION/apps/cert-manager/values/prod-values.yaml" \
  -n cert-manager \
  --wait --timeout 3m

info "cert-manager installed"

# ── Step 3.5: Wait for cert-manager CRDs ────────────────────────
step "Waiting for cert-manager CRDs"

kubectl wait --for=condition=Established \
  crd/certificates.cert-manager.io \
  crd/clusterissuers.cert-manager.io \
  --timeout=120s

info "cert-manager CRDs established"

# ── Step 4: cert-manager issuers ──────────────────────────────────
step "Installing cert-manager issuers"

helm dependency update "$SOLUTION/apps/cert-manager-issuers"

helm upgrade --install cluster-cert-manager-issuers "$SOLUTION/apps/cert-manager-issuers" \
  -n cert-manager \
  --wait --timeout 2m

info "cert-manager issuers installed"

# ── Step 5: Envoy Gateway ───────────────────────────────────────
step "Installing Envoy Gateway"

helm dependency update "$SOLUTION/apps/envoy-gateway"

helm upgrade --install cluster-envoy-gateway "$SOLUTION/apps/envoy-gateway" \
  -f "$SOLUTION/apps/envoy-gateway/values/prod-values.yaml" \
  -n envoy-gateway \
  --wait --timeout 3m

info "Envoy Gateway installed"

# ── Step 6: Longhorn ──────────────────────────────────────────────
step "Installing Longhorn"

if ! iscsiadm --version &>/dev/null 2>&1; then
  warn "iscsiadm not found on this machine."
  warn "On k3s/Linux: sudo apt install open-iscsi && sudo systemctl enable --now iscsid"
  warn "On Talos: rebuild nodes with the iscsi-tools extension from factory.talos.dev"
  err  "Fix iscsiadm first — Longhorn will crash without it."
fi

helm repo add longhorn https://charts.longhorn.io --force-update &>/dev/null
helm repo update longhorn &>/dev/null
helm dependency update "$SOLUTION/apps/longhorn"

helm upgrade --install cluster-longhorn "$SOLUTION/apps/longhorn" \
  -f "$SOLUTION/apps/longhorn/values/prod-values.yaml" \
  -n longhorn \
  --wait --timeout 5m

info "Longhorn installed"
kubectl get storageclass | grep longhorn || warn "longhorn StorageClass not found — check Longhorn pods"

# ── Step 7: Authentik ─────────────────────────────────────────────
step "Installing Authentik"

helm repo add authentik https://charts.goauthentik.io --force-update &>/dev/null
helm repo update authentik &>/dev/null
helm dependency update "$SOLUTION/apps/authentik"

helm upgrade --install cluster-authentik "$SOLUTION/apps/authentik" \
  -f "$SOLUTION/apps/authentik/values/prod-values.yaml" \
  --set-string "authentik.authentik.secret_key=${AUTHENTIK_SECRET_KEY}" \
  --set-string "authentik.authentik.bootstrap_password=${AUTHENTIK_BOOTSTRAP_PASSWORD}" \
  --set-string "authentik.authentik.bootstrap_email=${AUTHENTIK_BOOTSTRAP_EMAIL}" \
  --set-string "authentik.authentik.postgresql.password=${AUTHENTIK_PG_PASSWORD}" \
  --set-string "authentik.postgresql.auth.password=${AUTHENTIK_PG_PASSWORD}" \
  -n authentik \
  --wait --timeout 5m

info "Authentik installed"

# ── Step 8: Harbor ────────────────────────────────────────────────
step "Installing Harbor"

helm repo add harbor https://helm.goharbor.io --force-update &>/dev/null
helm repo update harbor &>/dev/null
helm dependency update "$SOLUTION/apps/harbor"

helm upgrade --install cluster-harbor "$SOLUTION/apps/harbor" \
  -f "$SOLUTION/apps/harbor/values/prod-values.yaml" \
  --set-string "harbor.harborAdminPassword=${HARBOR_ADMIN_PASSWORD}" \
  --set-string "harbor.secretKey=${HARBOR_SECRET_KEY}" \
  -n harbor \
  --wait --timeout 5m

info "Harbor installed"

# ── Step 8.5: Configure CA trust ─────────────────────────────────
step "Configuring CA trust for Harbor"

info "Running trust-harbor-ca.sh (requires sudo)"
sudo -E bash "$SOLUTION/scripts/trust-harbor-ca.sh"

info "Waiting for cluster to stabilize after k3s restart"
sleep 5
kubectl wait --for=condition=Ready nodes --all --timeout=120s
kubectl rollout status deployment -n harbor --timeout=120s 2>/dev/null || true

# ── Step 8.6: Create Harbor project and push images ──────────────
step "Setting up Harbor project and pushing images"

info "Waiting for Harbor API to respond"
HARBOR_URL="https://${HARBOR_HOST}"
for i in $(seq 1 30); do
  if curl -sk "${HARBOR_URL}/api/v2.0/health" | grep -q '"status":"healthy"'; then
    info "Harbor API is healthy"
    break
  fi
  [[ $i -eq 30 ]] && err "Harbor API did not become healthy within 60 seconds"
  sleep 2
done

info "Creating Harbor project: ${HARBOR_PROJECT}"
HTTP_CODE=$(curl -sk -o /dev/null -w '%{http_code}' \
  -u "${HARBOR_USER}:${HARBOR_ADMIN_PASSWORD}" \
  -H "Content-Type: application/json" \
  -X POST "${HARBOR_URL}/api/v2.0/projects" \
  -d "{\"project_name\":\"${HARBOR_PROJECT}\",\"metadata\":{\"public\":\"true\"}}")

case "$HTTP_CODE" in
  201) info "Project '${HARBOR_PROJECT}' created" ;;
  409) info "Project '${HARBOR_PROJECT}' already exists" ;;
  *)   err "Failed to create project (HTTP $HTTP_CODE)" ;;
esac

info "Pushing container images to Harbor"
bash "$SOLUTION/scripts/push-images.sh"

# ── Step 9: Deploy todo-app ───────────────────────────────────────
step "Deploying todo-app (pulling from Harbor)"

helm upgrade --install "$RELEASE_NAME" "${TODO_APP_CHART_ARGS[@]}" \
  -f "$CHART_VALUES" \
  "${TODO_APP_SET_ARGS[@]}" \
  -n todo \
  --wait --timeout 3m

info "todo-app deployed"

# ── Verify ────────────────────────────────────────────────────────
step "Verification"

echo ""
echo "MetalLB pods:"
kubectl get pods -n metallb-system --no-headers 2>/dev/null | awk '{printf "  %-50s %s\n", $1, $3}' || true

echo ""
echo "cert-manager pods:"
kubectl get pods -n cert-manager --no-headers | awk '{printf "  %-50s %s\n", $1, $3}'

echo ""
echo "Envoy Gateway pods:"
kubectl get pods -n envoy-gateway --no-headers | awk '{printf "  %-50s %s\n", $1, $3}'

echo ""
echo "Longhorn pods:"
kubectl get pods -n longhorn --no-headers | awk '{printf "  %-50s %s\n", $1, $3}'

echo ""
echo "Authentik pods:"
kubectl get pods -n authentik --no-headers | awk '{printf "  %-50s %s\n", $1, $3}'

echo ""
echo "Harbor pods:"
kubectl get pods -n harbor --no-headers | awk '{printf "  %-50s %s\n", $1, $3}'

echo ""
echo "todo-app pods:"
kubectl get pods -n todo --no-headers | awk '{printf "  %-50s %s\n", $1, $3}'

echo ""
echo "Gateway service:"
kubectl get svc -n envoy-gateway

GATEWAY_IP="$(kubectl get svc -n envoy-gateway -o jsonpath='{.items[?(@.spec.type=="LoadBalancer")].status.loadBalancer.ingress[0].ip}' 2>/dev/null || true)"
if [[ -z "$GATEWAY_IP" ]]; then
  GATEWAY_IP="$(kubectl get svc -n envoy-gateway -o jsonpath='{.items[?(@.spec.type=="LoadBalancer")].status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)"
fi

echo ""
info "Bootstrap complete."
if [[ -n "$GATEWAY_IP" ]]; then
  info "Add to /etc/hosts:  ${GATEWAY_IP}  todo.local longhorn.local authentik.local harbor.local"
else
  warn "Gateway EXTERNAL-IP not assigned yet — run: kubectl get svc -n envoy-gateway"
  warn "Then add to /etc/hosts:  <EXTERNAL-IP>  todo.local longhorn.local authentik.local harbor.local"
fi
echo ""
info "Services:"
info "  Harbor UI:    https://harbor.local  (login: admin / your HARBOR_ADMIN_PASSWORD)"
info "  todo-app:     https://todo.local"
info "  Longhorn UI:  https://longhorn.local"
info "  Authentik:    https://authentik.local"
echo ""
info "Image registry:"
info "  Frontend: ${HARBOR_HOST}/${HARBOR_PROJECT}/frontend:${IMAGE_TAG}"
info "  Backend:  ${HARBOR_HOST}/${HARBOR_PROJECT}/backend:${IMAGE_TAG}"
echo ""
info "Next steps — configure Authentik (same as Phase 07):"
info "  1. Open https://authentik.local  (login: akadmin / your bootstrap password)"
info "  2. Create Proxy Providers + Applications for todo-app and longhorn"
info "  3. Assign providers to the embedded outpost"
echo ""
info "To push a new image version:"
info "  1. Build: docker build -t frontend:1.1.0 ./application/frontend"
info "  2. Update IMAGE_TAG=1.1.0 in bootstrap/.env"
info "  3. Push:  ./scripts/push-images.sh"
info "  4. Upgrade: helm upgrade $RELEASE_NAME <chart> -n todo --set frontend.image.tag=1.1.0 ..."
