apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/todo-app
patches:
  - path: todo-app-chart.yaml
    target:
      kind: OCIRepository
      name: todo-app
  - path: todo-app-values.yaml
    target:
      kind: HelmRelease
      name: todo-app
