apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-ipaddresspool
  namespace: metallb-system
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  addresses:
    - 192.168.220.104/32
