{{- if not .Values.postgres.existingSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "todo-app.databaseSecretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  encryptedData:
    DATABASE_URI: cipher value
    POSTGRES_DB: cipher value
    POSTGRES_PASSWORD: cipher value
    POSTGRES_USER: cipher value
  template:
    metadata:
      name: {{ include "todo-app.databaseSecretName" . }}
      namespace: {{ .Release.Namespace | quote }}
      labels:
        {{- include "todo-app.labels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    type: Opaque
{{- end }}
